version: "3.7"
services:
  app_park-man:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: park-man
    container_name: park-man-app
    restart: unless-stopped
    working_dir: /var/www/park-man
    volumes:
      - ./:/var/www/park-man
    networks:
      - park-man-local-network
    depends_on:
        - park-man-db
  park-man-db:
      image: mysql:8.0
      restart: always
      environment:
          MYSQL_DATABASE: 'park-man-local-db'
          MYSQL_USER: 'dima'
          MYSQL_PASSWORD: 'dima123'
          MYSQL_ROOT_PASSWORD: 'root'
      ports:
          # <Port exposed> : < MySQL Port running inside container>
          - '3307:3306'
      expose:
          # Opens port 3306 on the container
          - '3306'
          # Where our data will be persisted
      volumes:
          - park-man-db:/va
      networks:
          - park-man-local-network
  nginx_park-man:
    image: nginx:1.18.0-alpine
    container_name: park-man-nginx
    restart: unless-stopped
    ports:
      - "8012:80"
    volumes:
      - ./public:/var/www/park-man/public
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
        - park-man-local-network
networks:
    park-man-local-network:
        external: true
volumes:
  my-datavolume:
  park-man-db:
